import { Listing, SiteConfig } from './types';

export const SITE_CONFIG: SiteConfig = {
  name: '제일부동산',
  phone: '051-123-4567',
  address: '부산광역시 해운대구 센텀중앙로 123, 제일빌딩 1층',
  email: 'jeil_realty@example.com',
  representative: '김제일',
  registrationNumber: '제 12345-2024-00001 호',
  themeColor: '#FF1493', // Deep Pink
  japaneseSupport: true,
};

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: '1',
    title: '해운대 엘시티 더샵 고층 오션뷰',
    type: '매매',
    category: '아파트',
    price: '35억 5,000만',
    location: '부산광역시 해운대구 중동',
    description: '해운대 최고의 랜드마크 엘시티 더샵입니다. 전면 오션뷰를 자랑하는 고층 매물로 내부 인테리어가 최상급입니다.',
    features: ['오션뷰', '풀옵션', '즉시입주', '주차편리'],
    imageUrl: 'https://picsum.photos/seed/apartment1/800/600',
    area: '186㎡',
    floor: '75층 / 85층',
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: '2',
    title: '센텀시티 역세권 대형 상가 임대',
    type: '월세',
    category: '상가',
    price: '5,000 / 350',
    location: '부산광역시 해운대구 우동',
    description: '센텀시티역 도보 3분 거리의 초역세권 상가입니다. 유동인구가 매우 많아 프랜차이즈 카페나 음식점으로 추천드립니다.',
    features: ['역세권', '무권리', '유동인구많음', '코너상가'],
    imageUrl: 'https://picsum.photos/seed/shop1/800/600',
    area: '120㎡',
    floor: '1층 / 15층',
    createdAt: Date.now() - 86400000 * 5,
  },
  {
    id: '3',
    title: '광안리 해변가 신축 오피스텔 첫입주',
    type: '전세',
    category: '오피스텔',
    price: '2억 8,000만',
    location: '부산광역시 수영구 민락동',
    description: '광안대교 뷰가 보이는 신축 오피스텔입니다. 첫 입주 매물로 매우 깨끗하며 보안이 철저합니다.',
    features: ['신축', '광안대교뷰', '풀빌트인', '보안우수'],
    imageUrl: 'https://picsum.photos/seed/officetel1/800/600',
    area: '45㎡',
    floor: '12층 / 20층',
    createdAt: Date.now() - 86400000 * 1,
  },
  {
    id: '4',
    title: '마린시티 제니스 조망권 좋은 세대',
    type: '매매',
    category: '아파트',
    price: '22억 8,000만',
    location: '부산광역시 해운대구 우동',
    description: '마린시티 두산위브더제니스입니다. 광안대교와 요트경기장 조망이 일품인 세대입니다.',
    features: ['고급단지', '조망권우수', '커뮤니티시설', '철저한보안'],
    imageUrl: 'https://picsum.photos/seed/apartment2/800/600',
    area: '157㎡',
    floor: '45층 / 80층',
    createdAt: Date.now() - 86400000 * 10,
  },
];
